server:
  compression:
    enabled: true
  port: 8761
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
zuul:
  prefix: /api
  routes:
    user-center:
      path: /user-center/**
      service-id: user-center
    service-1:
      path: /service-1/**
      service-id: service01
  sensitive-headers: Cookies
  host:
    connect-timeout-millis: 10000
ribbon:
  eureka:
    enabled: true
spring:
  application:
    name: gateway
#user-center:
#  ribbon:
#    listOfServers: 127.0.0.1:9001