spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
       url : jdbc:h2:mem:examples
       username : sa
       password :
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name : org.h2.Driver
hsweb:
    app:
      name: hsweb示例
      version: 3.0.0
    entity:
      mappings:
          -  source-base-package: org.hswebframework.web.entity.authorization
             target-base-package: org.hswebframework.web.entity.authorization
             mapping:
                UserEntity: SimpleUserEntity